# Limpieza de datos

In [151]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, accuracy_score

In [152]:
data = pd.read_csv('vivino.csv')

In [153]:
data

,winery,wine_name,year,price,score,country,wine_type,pairing,flavours,picture,price_quality,Uvas,Región,Estilo de vino,Contenido de alcohol
0,Quinta de Catralvos,Alicante Bouschet - Syrah,2021,€14.95,4.5,Portugal,Vino tinto,"Ternera, Ternera lechal, Aves, Pasta","ciruela, cereza negra",//images.vivino.com/thumbs/AwtSRa2ZSSWJE1AoViX...,¡Increíble relación calidad-precio!,"Alicante Bouschet,Shiraz/Syrah",Península de Setúbal,Sur Portugal Tinto,14%
1,Quinta do Ermizio,Vinha do Cuco,2023,€16.95,4.5,Portugal,Vino blanco,"Marisco, Aperitivos y tentempiés, Pescado blan...","lima, cítrico, limón",//images.vivino.com/thumbs/M2tFNe1GQQaqrU_wn-q...,¡Increíble relación calidad-precio!,"Loureiro,Alvarinho",Minho,Norte Portugal Blanco,12.5%
2,Sociedade Vinicola de Palmela,Personalizado,2022,€17.95,4.5,Portugal,Vino tinto,"Ternera, Ternera lechal, Aves, Pasta","vainilla, roble, chocol...",//images.vivino.com/thumbs/UgUGQSbaTSGQMHMk6zj...,¡Increíble relación calidad-precio!,Castelao,Palmela,Sur Portugal Tinto,13.5%
3,San Marzano,60 Sessantanni Old Vines Primitivo di Manduria,2018,€21.95,4.4,Italia,Vino tinto,"Ternera, Cordero, Aves, Pasta","vainilla, chocolate, ta...",//images.vivino.com/thumbs/tLtS1VwaRxCL25zZ-j6...,Buena relación calidad-precio,100% dePrimitivo,Primitivo di Manduria,Primitivo (Italia),14.5%
4,Puglia Pop,Fico Susumaniello,2022,€19.95,4.4,Italia,Vino tinto,"Ternera, Cordero, Pasta","vainilla, tabaco, café",//images.vivino.com/thumbs/XAKEoj1sR5SllZQ-x5N...,Buena relación calidad-precio,Susumaniello,Puglia,Sur Italia Tinto,14%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8416,Niepoort,Douro Redoma Branco,2021,€22.45,4.2,Portugal,Vino blanco,"Marisco, Aperitivos y tentempiés, Pescado blan...","manzana, albaricoque, m...",//images.vivino.com/thumbs/qSAfjOinQ2SWoemIPTX...,Buena relación calidad-precio,100% deRabigato,Douro,Norte Portugal Blanco,12.2%
8417,Niepoort,Douro Reserva Redoma Branco,2021,€49.35,4.2,Portugal,Vino blanco,"Marisco, Aperitivos y tentempiés, Pescado blan...","roble, vainilla, manteq...",//images.vivino.com/thumbs/zPbjKkMhTNGAH1Y3I09...,Relación calidad-precio razonable,100% deRabigato,Douro,Norte Portugal Blanco,11.5%
8418,Forjas del Salnés,Goliardo a Telleira Albariño,2021,€34.51,4.2,España,Vino blanco,"Marisco, Vegetariana, Pasta, Aperitivos y tent...","pera, melocotón, manzan...",//images.vivino.com/thumbs/YHiRsXtVRteasXHBETF...,Buena relación calidad-precio,100% deAlbariño,Rías Baixas,Albariño (España),12.5%
8419,Niepoort,V.V. Bical - Maria Gomes Vinhas Velhas,2018,€38.35,4.2,Portugal,Vino blanco,"Marisco, Pescado azul (salmón, atún, etc.), Ap...","minerales, miel, soluci...",//images.vivino.com/thumbs/fq2KfOb6QgyVmXeEsow...,Buena relación calidad-precio,"Bical,Maria Gomes",Bairrada,Central Portugal White,11%
8420,Celler Piñol,Finca Morenillo,2013,€45.72,4.2,España,Vino tinto,"Ternera, Ternera lechal, Aves, Pasta","roble, vainilla, chocol...",//images.vivino.com/thumbs/7kO5ZDbyR_mDgXL3jGa...,Buena relación calidad-precio,100% deMorenillo,Tarragona,Tinto (España),14.5%

## Ya que se han guardado varios vinos con el mismo nombre, bodega y año, se procederá a eliminar los duplicados

In [154]:
# Eliminar filas duplicadas que tienen el mismo nombre y año
data.drop_duplicates(subset=['winery', 'year', 'wine_name'], inplace=True)

# Verificar el resultado
data

,winery,wine_name,year,price,score,country,wine_type,pairing,flavours,picture,price_quality,Uvas,Región,Estilo de vino,Contenido de alcohol
0,Quinta de Catralvos,Alicante Bouschet - Syrah,2021,€14.95,4.5,Portugal,Vino tinto,"Ternera, Ternera lechal, Aves, Pasta","ciruela, cereza negra",//images.vivino.com/thumbs/AwtSRa2ZSSWJE1AoViX...,¡Increíble relación calidad-precio!,"Alicante Bouschet,Shiraz/Syrah",Península de Setúbal,Sur Portugal Tinto,14%
1,Quinta do Ermizio,Vinha do Cuco,2023,€16.95,4.5,Portugal,Vino blanco,"Marisco, Aperitivos y tentempiés, Pescado blan...","lima, cítrico, limón",//images.vivino.com/thumbs/M2tFNe1GQQaqrU_wn-q...,¡Increíble relación calidad-precio!,"Loureiro,Alvarinho",Minho,Norte Portugal Blanco,12.5%
2,Sociedade Vinicola de Palmela,Personalizado,2022,€17.95,4.5,Portugal,Vino tinto,"Ternera, Ternera lechal, Aves, Pasta","vainilla, roble, chocol...",//images.vivino.com/thumbs/UgUGQSbaTSGQMHMk6zj...,¡Increíble relación calidad-precio!,Castelao,Palmela,Sur Portugal Tinto,13.5%
3,San Marzano,60 Sessantanni Old Vines Primitivo di Manduria,2018,€21.95,4.4,Italia,Vino tinto,"Ternera, Cordero, Aves, Pasta","vainilla, chocolate, ta...",//images.vivino.com/thumbs/tLtS1VwaRxCL25zZ-j6...,Buena relación calidad-precio,100% dePrimitivo,Primitivo di Manduria,Primitivo (Italia),14.5%
4,Puglia Pop,Fico Susumaniello,2022,€19.95,4.4,Italia,Vino tinto,"Ternera, Cordero, Pasta","vainilla, tabaco, café",//images.vivino.com/thumbs/XAKEoj1sR5SllZQ-x5N...,Buena relación calidad-precio,Susumaniello,Puglia,Sur Italia Tinto,14%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8148,Niepoort,V.V. Bical - Maria Gomes Vinhas Velhas,2018,€38.35,4.2,Portugal,Vino blanco,"Marisco, Pescado azul (salmón, atún, etc.), Ap...","minerales, miel, soluci...",//images.vivino.com/thumbs/fq2KfOb6QgyVmXeEsow...,Buena relación calidad-precio,"Bical,Maria Gomes",Bairrada,Central Portugal White,11%
8149,Forjas del Salnés,Goliardo a Telleira Albariño,2021,€34.51,4.2,España,Vino blanco,"Marisco, Vegetariana, Pasta, Aperitivos y tent...","pera, melocotón, manzan...",//images.vivino.com/thumbs/YHiRsXtVRteasXHBETF...,Buena relación calidad-precio,100% deAlbariño,Rías Baixas,Albariño (España),12.5%
8150,Fernández de Piérola,Vitium Reserva,2015,€30.20,4.2,España,Vino tinto,"Ternera, Cordero, Ternera lechal, Aves","vainilla, café, chocola...",//images.vivino.com/thumbs/Sfpl41O_T2S__xayMq3...,Buena relación calidad-precio,Tempranillo,Rioja,Rioja Tinto (España),NaN
8232,Cota 45,Pandorga Tintilla de Rota,2022,€39.15,4.2,España,Vino tinto,"Ternera, Ternera lechal, Aves, Pasta","ciruela, cereza negra, ...",//images.vivino.com/thumbs/s0OuKAb-SYiyh9n3SP-...,Relación calidad-precio no disponible,Tintilla de Rota,Vino de España,Tinto (España),10%
8258,Celler Piñol,Finca Morenillo,2013,€45.72,4.2,España,Vino tinto,"Ternera, Ternera lechal, Aves, Pasta","roble, vainilla, chocol...",//images.vivino.com/thumbs/7kO5ZDbyR_mDgXL3jGa...,Buena relación calidad-precio,100% deMorenillo,Tarragona,Tinto (España),14.5%

## Transformación de price a tipo Float y year a tipo Int

In [155]:
# Convertir la columna 'price' a float
data['price'] = data['price'].str.replace('€', '').str.replace(',', '.').astype(float)

# Convertir la columna 'year' a int, reemplazando 'N.V.' por -1
data['year'] = data['year'].replace('N.V.', -1).astype(int)

In [156]:
data.value_counts('year')

year
 2021    358
 2020    348
 2019    316
 2022    312
 2018    185
 2023    156
 2017    106
 2016     84
 2015     46
 2014     23
 2013     15
-1        11
 2011     10
 2012      9
 2009      7
 2007      6
 2010      5
 2006      2
 1999      2
 2008      2
 2024      2
 2004      1
 1992      1
 1993      1
 1997      1
 2001      1
Name: count, dtype: int64

In [157]:
data.describe()

              year        price        score
count  2010.000000  2010.000000  2010.000000
mean   2008.477612    34.092836     4.224378
std     149.128995    14.336735     0.131888
min      -1.000000     7.050000     3.800000
25%    2018.000000    21.950000     4.200000
50%    2020.000000    34.950000     4.200000
75%    2021.000000    46.000000     4.300000
max    2024.000000    60.000000     4.600000

## Convertir la columna `wine_type`, `price_quality` y `country` en variables numéricas

In [158]:
# Asignar valores numéricos a los tipos de vino
data['wine_type'] = data['wine_type'].map({'Vino blanco': 1, 'Vino tinto': 2})

# Verificar el resultado
data['wine_type'].value_counts()

wine_type
2    1464
1     546
Name: count, dtype: int64

In [159]:
data['price_quality'].value_counts()

price_quality
Buena relación calidad-precio                   1002
Excelente relación calidad-precio                736
¡Increíble relación calidad-precio!              123
Relación calidad-precio razonable                 73
Relación calidad-precio no disponible             43
Mejor relación calidad-precio en otros vinos      13
Name: count, dtype: int64

In [160]:
# Asignar valores numéricos a los tipos de vino
data.loc[:, 'price_quality'] = data['price_quality'].map({
    'Relación calidad-precio no disponible': 1,
    'Mejor relación calidad-precio en otros vinos': 2,
    'Relación calidad-precio razonable': 3,
    'Buena relación calidad-precio': 4,
    'Excelente relación calidad-precio': 5,
    '¡Increíble relación calidad-precio!': 6})

In [161]:
data['price_quality'].value_counts()

price_quality
4.0    1002
5.0     736
6.0     123
3.0      73
1.0      43
2.0      13
Name: count, dtype: int64

In [162]:
data['country'].value_counts()

country
España            1029
Francia            392
Italia             360
Argentina           54
Alemania            40
Sudáfrica           32
Portugal            29
New Zealand         20
Estados Unidos      18
Austria              6
Uruguay              6
Australia            5
Chile                4
Croacia              4
Israel               3
Moldavia             3
Hungría              1
Albania              1
Eslovenia            1
Grecia               1
Líbano               1
Name: count, dtype: int64

In [163]:
# Identificamos los países más comunes
top_countries = data['country'].value_counts().nlargest(3).index

# Creamos una nueva columna 'country_grouped' que agrupa los países menos comunes en 'Other'
data['country_grouped'] = data['country'].apply(lambda x: x if x in top_countries else 'Other')

# comprobar el resultado
print(data['country_grouped'].value_counts())

country_grouped
España     1029
Francia     392
Italia      360
Other       229
Name: count, dtype: int64

In [164]:
# Asignar valores numéricos a los paises
data.loc[:, 'country_grouped'] = data['country_grouped'].map({
    'Other': 0,
    'Italia': 1,
    'Francia': 2,
    'España': 3})

# Verificar el resultado
print(data['country_grouped'].value_counts())

country_grouped
3    1029
2     392
1     360
0     229
Name: count, dtype: int64

In [165]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2010 entries, 0 to 8258
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   winery                2010 non-null   object
 1   wine_name             2010 non-null   object
 2   year                  2010 non-null   int64
 3   price                 2010 non-null   float64
 4   score                 2010 non-null   float64
 5   country               2010 non-null   object
 6   wine_type             2010 non-null   int64
 7   pairing               1891 non-null   object
 8   flavours              1889 non-null   object
 9   picture               2010 non-null   object
 10  price_quality         1990 non-null   object
 11  Uvas                  1991 non-null   object
 12  Región                2010 non-null   object
 13  Estilo de vino        2002 non-null   object
 14  Contenido de alcohol  1541 non-null   object
 15  country_grouped       2010 non-null   object
dtypes: float64(2), int64(2), object(12)
memory usage: 267.0+ KB

## Eliminamos columnas innecesarias y con bastantes nulos

In [166]:
data.drop(columns=['flavours', 'Uvas', 'Región', 'Contenido de alcohol'], inplace=True)

## Eliminamos los valores nulos y convertimos las columnas `wine_type` y `price_quality` y `country_grouped` a tipo int

In [167]:
data.dropna(inplace=True)

## Convertimos las columnas wine_type y price_quality a tipo int

data['wine_type'] = data['wine_type'].astype(int)
data['price_quality'] = data['price_quality'].astype(int)
data['country_grouped'] = data['country_grouped'].astype(int)

In [168]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1874 entries, 0 to 8258
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   winery           1874 non-null   object
 1   wine_name        1874 non-null   object
 2   year             1874 non-null   int64
 3   price            1874 non-null   float64
 4   score            1874 non-null   float64
 5   country          1874 non-null   object
 6   wine_type        1874 non-null   int64
 7   pairing          1874 non-null   object
 8   picture          1874 non-null   object
 9   price_quality    1874 non-null   int64
 10  Estilo de vino   1874 non-null   object
 11  country_grouped  1874 non-null   int64
dtypes: float64(2), int64(4), object(6)
memory usage: 190.3+ KB

In [169]:
# Guardar el DataFrame limpio en un archivo CSV
data.to_csv('vivino_clean.csv', index=False)